version: '3.9'

services:
  # Backend (Django)
  backend:
    build:
      context: ./backend
    container_name: barterhub-backend
    command: >
      sh -c "python manage.py migrate && python manage.py collectstatic --noinput && gunicorn backend.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - ./backend:/app
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      - db
    networks:
      - app-network

  # Frontend (React)
  frontend:
    build:
      context: ./frontend
    container_name: barterhub-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - app-network

  # Database (PostgreSQL)
  db:
    image: postgres:15
    container_name: barterhub-db
    environment:
      POSTGRES_DB: barterhub
      POSTGRES_USER: barteruser
      POSTGRES_PASSWORD: barterpass
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    networks:
      - app-network

# Volumes to persist PostgreSQL data and serve static/media files
volumes:
  postgres_data:
  static_volume:
  media_volume:

# Networks to isolate communication between containers
networks:
  app-network:
    driver: bridge
