# Generated by Django 5.2.3 on 2025-07-01 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_seed_categories'),
        ('items', '0004_skip'),
    ]

    operations = [
    ]
