# Generated by Django 5.2.3 on 2025-06-24 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_match_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='is_traded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='user1_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='user2_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
