# Generated by Django 5.2.3 on 2025-06-22 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_offer_recipient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='recipient',
        ),
    ]
