# Generated by Django 5.2.3 on 2025-06-22 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_remove_item_category_item_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('matched', 'Matched'), ('traded', 'Traded')], default='active', max_length=10),
        ),
    ]
