# Generated by Django 5.2.3 on 2025-06-25 00:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_alter_item_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Skip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skipped_at', models.DateTimeField(auto_now_add=True)),
                ('skipped_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skipped_by', to='items.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skips', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'skipped_item')},
            },
        ),
    ]
